<?php

namespace Database\Seeders;

use App\Models\Recipe;
use App\Models\User;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run()
    {
        $user = User::first(); // assign all recipes to the first user (or random later)

        $recipes = [
            [
                "name" => "Spaghetti Carbonara",
                "description" => "Creamy Italian pasta made with eggs, cheese, pancetta, and black pepper.",
                "ingredients" => "200g spaghetti\n2 eggs\n50g parmesan\n100g pancetta\nSalt and pepper",
                "instructions" => "1. Boil pasta.\n2. Cook pancetta.\n3. Mix eggs and cheese.\n4. Combine all while hot.",
                "difficulty" => "Easy",
                "cuisine" => "Italian",
                "time_minutes" => 25,
                "calories" => 520,
                "protein" => 22,
                "fat" => 18,
                "carbs" => 62,
                "image" => "food/carbonara.jpg",
            ],
            [
                "name" => "Chicken Teriyaki Bowl",
                "description" => "Japanese-style grilled chicken glazed with sweet teriyaki sauce.",
                "ingredients" => "200g chicken thighs\nSoy sauce\nMirin\nSugar\nSteamed rice",
                "instructions" => "1. Mix sauce.\n2. Cook chicken.\n3. Add sauce and reduce.\n4. Serve with rice.",
                "difficulty" => "Easy",
                "cuisine" => "Asian",
                "time_minutes" => 30,
                "calories" => 480,
                "protein" => 35,
                "fat" => 12,
                "carbs" => 60,
                "image" => "food/teriyaki.jpg",
            ],
            [
                "name" => "Beef Tacos",
                "description" => "Crispy tacos filled with seasoned beef, lettuce, cheese, and salsa.",
                "ingredients" => "200g ground beef\nTaco shells\nCheese\nLettuce\nSalsa",
                "instructions" => "1. Cook beef.\n2. Season.\n3. Assemble tacos with toppings.",
                "difficulty" => "Medium",
                "cuisine" => "Mexican",
                "time_minutes" => 20,
                "calories" => 430,
                "protein" => 25,
                "fat" => 15,
                "carbs" => 45,
                "image" => "food/tacos.jpg",
            ],
            [
                "name" => "Grilled Salmon with Lemon",
                "description" => "Fresh salmon grilled to perfection with a citrusy lemon butter sauce.",
                "ingredients" => "2 salmon fillets\nButter\nLemon\nSalt\nPepper",
                "instructions" => "1. Season salmon.\n2. Grill.\n3. Add lemon butter.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 15,
                "calories" => 390,
                "protein" => 34,
                "fat" => 20,
                "carbs" => 5,
                "image" => "food/salmon.jpg",
            ],
            [
                "name" => "Chicken Caesar Salad",
                "description" => "Classic Caesar salad topped with grilled chicken breast.",
                "ingredients" => "Chicken breast\nRomaine lettuce\nCaesar dressing\nCroutons\nParmesan",
                "instructions" => "1. Grill chicken.\n2. Toss salad.\n3. Add dressing and cheese.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 15,
                "calories" => 350,
                "protein" => 28,
                "fat" => 16,
                "carbs" => 18,
                "image" => "food/caesar.jpg",
            ],
            [
                "name" => "Margherita Pizza",
                "description" => "Classic Neapolitan pizza with tomato, mozzarella, and basil.",
                "ingredients" => "Pizza dough\nTomato sauce\nMozzarella\nBasil",
                "instructions" => "1. Prepare dough.\n2. Add toppings.\n3. Bake at high heat.",
                "difficulty" => "Medium",
                "cuisine" => "Italian",
                "time_minutes" => 35,
                "calories" => 600,
                "protein" => 22,
                "fat" => 20,
                "carbs" => 70,
                "image" => "food/margherita.jpg",
            ],

            [
                "name" => "Pad Thai",
                "description" => "Thai stir-fried noodles with shrimp, tofu, and tamarind sauce.",
                "ingredients" => "Rice noodles\nShrimp\nEggs\nBean sprouts\nPeanuts\nTamarind sauce",
                "instructions" => "1. Soften noodles.\n2. Stir fry ingredients.\n3. Add sauce.",
                "difficulty" => "Medium",
                "cuisine" => "Asian",
                "time_minutes" => 25,
                "calories" => 510,
                "protein" => 24,
                "fat" => 14,
                "carbs" => 68,
                "image" => "food/padthai.jpg",
            ],
            [
                "name" => "Ramen Bowl",
                "description" => "Japanese ramen with pork broth, noodles, egg, and vegetables.",
                "ingredients" => "Ramen noodles\nPork broth\nEgg\nNori\nGreen onions",
                "instructions" => "1. Cook broth.\n2. Boil noodles.\n3. Assemble bowl.",
                "difficulty" => "Hard",
                "cuisine" => "Asian",
                "time_minutes" => 45,
                "calories" => 650,
                "protein" => 30,
                "fat" => 20,
                "carbs" => 80,
                "image" => "food/ramen.jpg",
            ],
            [
                "name" => "Chocolate Chip Cookies",
                "description" => "Chewy chocolate chip cookies with a golden crisp edge.",
                "ingredients" => "Flour\nSugar\nButter\nChocolate Chips\nEggs",
                "instructions" => "1. Mix dough.\n2. Scoop.\n3. Bake.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 18,
                "calories" => 150,
                "protein" => 2,
                "fat" => 7,
                "carbs" => 22,
                "image" => "food/cookies.jpg",
            ],
            [
                "name" => "Butter Chicken",
                "description" => "Indian creamy tomato-based chicken curry.",
                "ingredients" => "Chicken\nTomatoes\nCream\nButter\nSpices",
                "instructions" => "1. Cook chicken with spices.\n2. Add tomato sauce.\n3. Stir in cream.",
                "difficulty" => "Medium",
                "cuisine" => "Asian",
                "time_minutes" => 40,
                "calories" => 610,
                "protein" => 36,
                "fat" => 28,
                "carbs" => 34,
                "image" => "food/butterchicken.jpg",
            ],
            [
                "name" => "Greek Salad",
                "description" => "Refreshing salad with feta cheese, olives, cucumber, and tomatoes.",
                "ingredients" => "Feta\nOlives\nTomatoes\nCucumber\nOlive oil",
                "instructions" => "1. Chop vegetables.\n2. Add feta.\n3. Drizzle olive oil.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 10,
                "calories" => 210,
                "protein" => 8,
                "fat" => 12,
                "carbs" => 18,
                "image" => "food/greeksalad.jpg",
            ],
            [
                "name" => "BBQ Ribs",
                "description" => "Slow-cooked BBQ pork ribs with smoky sauce.",
                "ingredients" => "Pork ribs\nBBQ sauce\nSalt\nPepper",
                "instructions" => "1. Season.\n2. Slow cook.\n3. Glaze with sauce.",
                "difficulty" => "Hard",
                "cuisine" => "American",
                "time_minutes" => 120,
                "calories" => 780,
                "protein" => 48,
                "fat" => 52,
                "carbs" => 22,
                "image" => "food/ribs.jpg",
            ],
            [
                "name" => "French Toast",
                "description" => "Soft bread soaked in egg mixture and pan-fried to golden perfection.",
                "ingredients" => "Bread\nEggs\nMilk\nSugar\nCinnamon",
                "instructions" => "1. Mix egg batter.\n2. Dip bread.\n3. Cook.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 12,
                "calories" => 290,
                "protein" => 9,
                "fat" => 12,
                "carbs" => 32,
                "image" => "food/frenchtoast.jpg",
            ],
            [
                "name" => "Shrimp Fried Rice",
                "description" => "Classic fried rice with shrimp, egg, and vegetables.",
                "ingredients" => "Shrimp\nRice\nEggs\nVegetables\nSoy sauce",
                "instructions" => "1. Stir fry shrimp.\n2. Add rice.\n3. Add soy sauce.",
                "difficulty" => "Easy",
                "cuisine" => "Asian",
                "time_minutes" => 15,
                "calories" => 450,
                "protein" => 22,
                "fat" => 10,
                "carbs" => 62,
                "image" => "food/friedrice.jpg",
            ],
            [
                "name" => "Lasagna",
                "description" => "Layered Italian pasta with meat sauce and cheese.",
                "ingredients" => "Lasagna sheets\nCheese\nTomato sauce\nGround beef",
                "instructions" => "1. Prepare sauce.\n2. Layer.\n3. Bake.",
                "difficulty" => "Hard",
                "cuisine" => "Italian",
                "time_minutes" => 60,
                "calories" => 700,
                "protein" => 35,
                "fat" => 32,
                "carbs" => 68,
                "image" => "food/lasagna.jpg",
            ],
            [
                "name" => "Pancakes",
                "description" => "Fluffy pancakes topped with maple syrup.",
                "ingredients" => "Flour\nMilk\nEggs\nSugar\nButter",
                "instructions" => "1. Mix batter.\n2. Pour on pan.\n3. Flip.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 10,
                "calories" => 220,
                "protein" => 6,
                "fat" => 7,
                "carbs" => 32,
                "image" => "food/pancakes.jpg",
            ],
            [
                "name" => "Tuna Sandwich",
                "description" => "Quick tuna sandwich with mayo and crunchy vegetables.",
                "ingredients" => "Tuna\nBread\nMayo\nOnion\nLettuce",
                "instructions" => "1. Mix tuna.\n2. Toast bread.\n3. Assemble sandwich.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 8,
                "calories" => 300,
                "protein" => 20,
                "fat" => 10,
                "carbs" => 35,
                "image" => "food/tunasandwich.jpg",
            ],
            [
                "name" => "Chicken Alfredo",
                "description" => "Creamy pasta dish with grilled chicken and Alfredo sauce.",
                "ingredients" => "Chicken\nPasta\nCream\nGarlic\nParmesan",
                "instructions" => "1. Cook pasta.\n2. Cook chicken.\n3. Make sauce.\n4. Combine.",
                "difficulty" => "Medium",
                "cuisine" => "Italian",
                "time_minutes" => 30,
                "calories" => 650,
                "protein" => 30,
                "fat" => 28,
                "carbs" => 60,
                "image" => "food/alfredo.jpg",
            ],
            [
                "name" => "Sushi Rolls",
                "description" => "Japanese rice rolls with vegetables and seafood.",
                "ingredients" => "Sushi rice\nNori\nCucumber\nCrab sticks\nAvocado",
                "instructions" => "1. Cook rice.\n2. Roll ingredients.\n3. Slice.",
                "difficulty" => "Hard",
                "cuisine" => "Asian",
                "time_minutes" => 50,
                "calories" => 350,
                "protein" => 12,
                "fat" => 6,
                "carbs" => 60,
                "image" => "food/sushi.jpg",
            ],
            [
                "name" => "Steak with Garlic Butter",
                "description" => "Juicy pan-seared steak topped with garlic herb butter.",
                "ingredients" => "Steak\nButter\nGarlic\nHerbs",
                "instructions" => "1. Season steak.\n2. Sear.\n3. Add butter.",
                "difficulty" => "Medium",
                "cuisine" => "American",
                "time_minutes" => 20,
                "calories" => 700,
                "protein" => 50,
                "fat" => 45,
                "carbs" => 2,
                "image" => "food/steak.jpg",
            ],
            [
                "name" => "Veggie Stir Fry",
                "description" => "Colorful vegetable stir-fry with soy garlic sauce.",
                "ingredients" => "Broccoli\nCarrots\nBell peppers\nSoy sauce\nGarlic",
                "instructions" => "1. Stir fry veggies.\n2. Add sauce.",
                "difficulty" => "Easy",
                "cuisine" => "Asian",
                "time_minutes" => 12,
                "calories" => 200,
                "protein" => 5,
                "fat" => 4,
                "carbs" => 35,
                "image" => "food/stirfry.jpg",
            ]
        ];

        foreach ($recipes as $recipe) {
            Recipe::create(array_merge($recipe, [
                "user_id" => $user->id,
                "rating" => 0,
            ]));
        }
    }
}
