<?php

namespace Database\Seeders;

use App\Models\Recipe;
use App\Models\User;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run()
    {
        $user = User::first();

        $recipes = [
            [
                "name" => "Spaghetti Carbonara",
                "description" => "Creamy Italian pasta made with eggs, cheese, pancetta, and black pepper.",
                "ingredients" => "200g spaghetti\n2 eggs\n50g parmesan\n100g pancetta\nSalt and pepper",
                "instructions" => "1. Boil pasta.\n2. Cook pancetta.\n3. Mix eggs and cheese.\n4. Combine all while hot.",
                "difficulty" => "Easy",
                "cuisine" => "Italian",
                "time_minutes" => 25,
                "calories" => 520,
                "protein" => 22,
                "fat" => 18,
                "carbs" => 62,
                "image" => "food/carbonara.jpg",
            ],
            [
                "name" => "Chicken Teriyaki Bowl",
                "description" => "Juicy glazed chicken thigh bites served over steamed rice with crisp-tender vegetables and a glossy house-made teriyaki sauce.",
                "ingredients" => "600 g boneless skinless chicken thighs\n2 cups jasmine rice\n1 cup broccoli florets\n1 medium carrot, julienned\n1 small bell pepper, sliced\n3 Tbsp soy sauce\n2 Tbsp mirin\n2 Tbsp sake (or water)\n1 Tbsp sugar\n1 tsp grated ginger\n1 clove garlic, minced\n1 tsp cornstarch + 1 Tbsp water\n1 Tbsp sesame oil\n1 Tbsp neutral oil\nSesame seeds & sliced scallion for garnish",
                "instructions" => "1. Rinse rice; cook in 3 cups water until fluffy (15 min).\n2. Cut chicken into 2 cm chunks; pat dry.\n3. Whisk soy, mirin, sake, sugar, ginger, garlic; reserve.\n4. Heat neutral oil in skillet; sear chicken 3 min per side until golden.\n5. Pour in teriyaki mix; simmer 3 min until chicken is glazed.\n6. Stir cornstarch slurry; add to pan, cook 30 sec until thick and glossy.\n7. Steam broccoli & carrot 3 min until bright and crisp-tender.\n8. Assemble bowls: rice, veg, chicken, extra sauce drizzle, sesame seeds & scallion.",
                "difficulty" => "Easy",
                "cuisine" => "Japanese",
                "time_minutes" => 25,
                "calories" => 720,
                "protein" => 45,
                "fat" => 18,
                "carbs" => 92,
                "image" => "food/teriyaki.jpg",
            ],
            [
                "name" => "Beef Tacos",
                "description" => "Crispy tacos filled with seasoned beef, lettuce, cheese, and salsa.",
                "ingredients" => "200g ground beef\nTaco shells\nCheese\nLettuce\nSalsa",
                "instructions" => "1. Cook beef.\n2. Season.\n3. Assemble tacos with toppings.",
                "difficulty" => "Medium",
                "cuisine" => "Mexican",
                "time_minutes" => 20,
                "calories" => 430,
                "protein" => 25,
                "fat" => 15,
                "carbs" => 45,
                "image" => "food/tacos.jpg",
            ],
            [
                "name" => "Grilled Salmon with Lemon",
                "description" => "Flaky salmon fillets kissed by smoky grill marks, finished with a bright lemon-garlic butter and a sprinkle of fresh herbs.",
                "ingredients" => "4 salmon fillets (180 g each, skin-on)\n2 Tbsp olive oil\n1 lemon (zest + juice)\n3 Tbsp unsalted butter\n2 cloves garlic, minced\n1 Tbsp chopped fresh dill\n1 Tbsp chopped fresh parsley\nSalt & cracked black pepper\nLemon wedges for serving",
                "instructions" => "1. Pat salmon dry; brush with olive oil, season generously with salt, pepper, and lemon zest.\n2. Pre-heat grill to medium-high (200 °C); clean and oil grates.\n3. Place salmon skin-side up; grill 4 min without moving.\n4. Flip; grill 3 min more until internal temp hits 52 °C.\n5. Meanwhile melt butter in small pan; add garlic, cook 30 sec, stir in lemon juice and herbs.\n6. Transfer salmon to plates; spoon lemon-garlic butter over top.\n7. Serve immediately with extra lemon wedges.",
                "difficulty" => "Easy",
                "cuisine" => "Western",
                "time_minutes" => 15,
                "calories" => 380,
                "protein" => 34,
                "fat" => 26,
                "carbs" => 2,
                "image" => "food/salmon.jpg",
            ],
            [
                "name" => "Chicken Caesar Salad",
                "description" => "Crisp romaine hearts tossed in creamy house-made Caesar dressing, topped with juicy grilled chicken, crunchy parmesan croutons and shaved Parmigiano-Reggiano.",
                "ingredients" => "2 large romaine lettuce hearts\n400 g boneless skinless chicken breasts\n2 slices day-old bread (cubed)\n¼ cup grated Parmesan\n¼ cup shaved Parmigiano-Reggiano\n2 Tbsp olive oil\n1 egg yolk\n1 tsp Dijon mustard\n1 tsp Worcestershire sauce\n1 anchovy fillet (minced)\n1 clove garlic (minced)\nJuice of ½ lemon
                3 Tbsp neutral oil
                Salt & cracked black pepper",
                "instructions" => "1. Season chicken with salt, pepper & 1 tsp olive oil; grill 6 min per side until 75 °C internal. Rest 5 min, slice thin.\n2. Cube bread; toss with 1 Tbsp oil, grated Parmesan, pinch salt. Bake 8 min at 200 °C until golden croutons.\n3. Whisk egg yolk, mustard, anchovy, garlic, lemon juice, Worcestershire; slowly drizzle in 3 Tbsp oil to emulsify. Season.\n4. Tear romaine into large bowl; add dressing, toss to coat.\n5. Top with sliced chicken, croutons and shaved Parmigiano. Serve immediately.",
                "difficulty" => "Medium",
                "cuisine" => "American",
                "time_minutes" => 20,
                "calories" => 480,
                "protein" => 42,
                "fat" => 28,
                "carbs" => 18,
                "image" => "food/caesar.jpg",
            ],
            [
                "name" => "Margherita Pizza",
                "description" => "Classic Neapolitan pizza with tomato, mozzarella, and basil.",
                "ingredients" => "Pizza dough\nTomato sauce\nMozzarella\nBasil",
                "instructions" => "1. Prepare dough.\n2. Add toppings.\n3. Bake at high heat.",
                "difficulty" => "Medium",
                "cuisine" => "Italian",
                "time_minutes" => 35,
                "calories" => 600,
                "protein" => 22,
                "fat" => 20,
                "carbs" => 70,
                "image" => "food/margherita.jpg",
            ],

            [
                "name" => "Pad Thai",
                "description" => "Thai stir-fried noodles with shrimp, tofu, and tamarind sauce.",
                "ingredients" => "Rice noodles\nShrimp\nEggs\nBean sprouts\nPeanuts\nTamarind sauce",
                "instructions" => "1. Soften noodles.\n2. Stir fry ingredients.\n3. Add sauce.",
                "difficulty" => "Medium",
                "cuisine" => "Asian",
                "time_minutes" => 25,
                "calories" => 510,
                "protein" => 24,
                "fat" => 14,
                "carbs" => 68,
                "image" => "food/padthai.jpg",
            ],
            [
                "name" => "Ramen Bowl",
                "description" => "Japanese ramen with pork broth, noodles, egg, and vegetables.",
                "ingredients" => "Ramen noodles\nPork broth\nEgg\nNori\nGreen onions",
                "instructions" => "1. Cook broth.\n2. Boil noodles.\n3. Assemble bowl.",
                "difficulty" => "Hard",
                "cuisine" => "Asian",
                "time_minutes" => 45,
                "calories" => 650,
                "protein" => 30,
                "fat" => 20,
                "carbs" => 80,
                "image" => "food/ramen.jpg",
            ],
            [
                "name" => "Chocolate Chip Cookies",
                "description" => "Chewy chocolate chip cookies with a golden crisp edge.",
                "ingredients" => "Flour\nSugar\nButter\nChocolate Chips\nEggs",
                "instructions" => "1. Mix dough.\n2. Scoop.\n3. Bake.",
                "difficulty" => "Easy",
                "cuisine" => "Italian",
                "time_minutes" => 18,
                "calories" => 150,
                "protein" => 2,
                "fat" => 7,
                "carbs" => 22,
                "image" => "food/cookies.jpg",
            ],
            [
                "name" => "Butter Chicken",
                "description" => "Tender chicken pieces simmered in a velvety tomato-cashew sauce enriched with butter and cream, finished with a whisper of fenugreek.",
                "ingredients" => "600 g boneless chicken thighs (2 cm chunks)\n1 cup plain yogurt\n2 Tbsp lime juice\n1 Tbsp garam masala\n1 tsp Kashmiri chilli powder\n1 tsp turmeric\nSalt to taste\n3 Tbsp butter\n1 Tbsp neutral oil\n1 medium onion (fine dice)\n4 cloves garlic (minced)\n1 Tbsp grated ginger\n400 g crushed tomatoes\n¼ cup cashew nuts (soaked 15 min, blended smooth)\n½ cup heavy cream
                1 tsp dried fenugreek leaves (kasoori methi)
                Fresh cilantro for garnish",
                "instructions" => "1. Marinate chicken in yogurt, lime juice, half the garam masala, chilli, turmeric & salt 30 min (overnight best).\n2. Heat oil in heavy pot; sear chicken 3 min per side until lightly charred. Set aside.\n3. Melt 2 Tbsp butter; sauté onion until golden, 6 min. Add garlic & ginger, cook 1 min.\n4. Stir in tomatoes; simmer 10 min until thick. Blend smooth with cashew paste.\n5. Return sauce to pot; add chicken, cream, remaining garam masala, kasoori methi. Simmer 5 min until chicken is 75 °C.\n6. Swirl in final 1 Tbsp butter, adjust salt. Garnish with cilantro; serve hot with basmati rice or naan.",
                "difficulty" => "Medium",
                "cuisine" => "Indian",
                "time_minutes" => 45,
                "calories" => 560,
                "protein" => 38,
                "fat" => 42,
                "carbs" => 14,
                "image" => "food/butterchicken.jpg",
            ],
            [
                "name" => "Greek Salad",
                "description" => "A sun-kissed medley of juicy tomatoes, crisp cucumbers, briny olives and creamy feta, tossed in a bright oregano-lemon vinaigrette.",
                "ingredients" => "3 ripe tomatoes (cut into wedges)\n1 large cucumber (partially peeled, sliced into half-moons)\n1 small red onion (thin half-rings)\n1 green bell pepper (sliced into rings)\n½ cup Kalamata olives (whole, pits in)\n200 g block feta cheese (cut into 2 cm cubes)\n3 Tbsp extra-virgin olive oil\n1 Tbsp red-wine vinegar\nJuice of ½ lemon
                ½ tsp dried oregano
                Pinch of sea salt & cracked black pepper",
                "instructions" => "1. Combine tomatoes, cucumber, onion, bell pepper and olives in a large bowl; gently toss.\n2. Whisk olive oil, vinegar, lemon juice, oregano, salt & pepper until emulsified.\n3. Pour dressing over vegetables; toss to coat.\n4. Top with feta slabs, sprinkle extra oregano, drizzle a little more oil.\n5. Serve immediately with crusty bread to mop up the juices.",
                "difficulty" => "Easy",
                "cuisine" => "Greek",
                "time_minutes" => 10,
                "calories" => 320,
                "protein" => 8,
                "fat" => 28,
                "carbs" => 12,
                "image" => "food/greeksalad.jpg",
            ],
            [
                "name" => "BBQ Ribs",
                "description" => "Slow-cooked BBQ pork ribs with smoky sauce.",
                "ingredients" => "Pork ribs\nBBQ sauce\nSalt\nPepper",
                "instructions" => "1. Season.\n2. Slow cook.\n3. Glaze with sauce.",
                "difficulty" => "Hard",
                "cuisine" => "American",
                "time_minutes" => 120,
                "calories" => 780,
                "protein" => 48,
                "fat" => 52,
                "carbs" => 22,
                "image" => "food/ribs.jpg",
            ],
            [
                "name" => "French Toast",
                "description" => "Soft bread soaked in egg mixture and pan-fried to golden perfection.",
                "ingredients" => "Bread\nEggs\nMilk\nSugar\nCinnamon",
                "instructions" => "1. Mix egg batter.\n2. Dip bread.\n3. Cook.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 12,
                "calories" => 290,
                "protein" => 9,
                "fat" => 12,
                "carbs" => 32,
                "image" => "food/frenchtoast.jpg",
            ],
            [
                "name" => "Shrimp Fried Rice",
                "description" => "Wok-seared rice studded with plump shrimp, golden egg, crisp peas and carrots, kissed with soy and a hint of sesame.",
                "ingredients" => "3 cups day-old cooked jasmine rice (cold)\n300 g raw shrimp (peeled, deveined)\n2 large eggs (beaten)\n½ cup frozen peas & carrots mix (thawed)\n3 Tbsp neutral oil\n2 Tbsp light soy sauce\n1 Tbsp oyster sauce
                ½ tsp sesame oil
                2 cloves garlic (minced)
                2 stalks green onion (sliced)
                Salt & white pepper to taste",
                "instructions" => "1. Heat 1 Tbsp oil in hot wok; scramble eggs until just set, break into small pieces, remove.\n2. Add 1 Tbsp oil; sear shrimp 1 min per side until pink, remove.\n3. Add remaining oil and garlic; stir-fry 20 sec. Add peas & carrots, toss 30 sec.\n4. Fluff in cold rice; press and toss until grains are hot and separated, 2 min.\n5. Return shrimp and eggs; splash soy & oyster sauces, sesame oil, season with salt & white pepper.\n6. Stir-fry everything 1 min. Finish with green onions; serve piping hot.",
                "difficulty" => "Easy",
                "cuisine" => "Chinese",
                "time_minutes" => 15,
                "calories" => 480,
                "protein" => 24,
                "fat" => 18,
                "carbs" => 58,
                "image" => "food/friedrice.jpg",
            ],
            [
                "name" => "Lasagna",
                "description" => "Layered Italian pasta with meat sauce and cheese.",
                "ingredients" => "Lasagna sheets\nCheese\nTomato sauce\nGround beef",
                "instructions" => "1. Prepare sauce.\n2. Layer.\n3. Bake.",
                "difficulty" => "Hard",
                "cuisine" => "Italian",
                "time_minutes" => 60,
                "calories" => 700,
                "protein" => 35,
                "fat" => 32,
                "carbs" => 68,
                "image" => "food/lasagna.jpg",
            ],
            [
                "name" => "Gado-Gado (Peanut-Sauce Veggie Salad)",
                "description" => "A vibrant rainbow of steamed vegetables, tofu and boiled eggs draped in a lighter, sugar-free Indonesian peanut sauce for a fiber-rich, protein-packed bite.",
                "ingredients" => "200 g mixed cabbage & bean sprouts (blanched)\n150 g green beans (trimmed, steamed)\n2 medium carrots (julienned, steamed)\n100 g baby spinach (blanched)\n150 g firm tofu (cubed, pan-seared)\n2 hard-boiled eggs (quartered)\n2 medium potatoes (boiled, sliced)\nSpice paste: 2 cloves garlic, 2 bird-eye chilies, ½ tsp salt\nSauce: ½ cup roasted peanuts + ¼ cup warm water (blitz smooth), 1 tsp tamarind, 1 Tbsp sweet soy (low-sodium), juice of ½ lime\nGarnish: crispy shallots & lime wedges",
                "instructions" => "1. Steam or blanch each vegetable 2–3 min until bright and just tender; chill quickly to keep crunch.\n2. Blend spice paste; mix into peanut puree with tamarind, sweet soy, lime juice and enough hot water for pourable dressing.\n3. Arrange vegetables, tofu, potatoes and eggs on a platter.\n4. Drizzle warm peanut sauce generously, sprinkle crispy shallots; serve with extra lime.",
                "difficulty" => "Easy",
                "cuisine" => "Indonesian",
                "time_minutes" => 25,
                "calories" => 420,
                "protein" => 22,
                "fat" => 20,
                "carbs" => 42,
                "image" => "food/gado.jpg",
            ],
            [
                "name" => "Tuna Sandwich",
                "description" => "A classic deli-style sandwich loaded with flaky tuna, crisp celery, and a tangy mayo-mustard dressing, tucked between soft whole-wheat toast.",
                "ingredients" => "2 cans tuna in water (5 oz / 142 g each, drained)\n2 Tbsp mayonnaise\n1 tsp Dijon mustard\n1 Tbsp lemon juice\n¼ cup finely diced celery\n2 Tbsp minced red onion\nSalt & cracked black pepper to taste\n4 slices whole-wheat bread (toasted)\n1 cup baby lettuce or arugula\n4 thin tomato slices",
                "instructions" => "1. In a bowl flake tuna; add mayo, mustard, lemon juice, celery, onion, season and mix well.\n2. Toast bread until golden and crisp.\n3. Layer lettuce and tomato on two slices; divide tuna salad evenly on top.\n4. Crown with remaining toast; press gently, slice in half and serve immediately.",
                "difficulty" => "Easy",
                "cuisine" => "American",
                "time_minutes" => 10,
                "calories" => 360,
                "protein" => 28,
                "fat" => 14,
                "carbs" => 32,
                "image" => "food/tunasandwich.jpg",
            ],
            [
                "name" => "Chicken Alfredo",
                "description" => "Tender fettuccine in a rich, garlicky parmesan-cream sauce topped with juicy grilled chicken.",
                "ingredients" => "400 g fettuccine\n500 g chicken breast\n200 ml heavy cream\n80 g butter\n100 g Parmesan\n3 cloves garlic\n2 Tbsp olive oil\nSalt & pepper\nParsley",
                "instructions" => "1. Cook fettuccine until al dente; drain.\n2. Season and sear chicken 6-7 min per side; rest 5 min then slice.\n3. Melt butter, sauté garlic 30 sec.\n4. Add cream, simmer, whisk in Parmesan until thick.\n5. Toss pasta and chicken in sauce; season and garnish.",
                "difficulty" => "Medium",
                "cuisine" => "Italian",
                "time_minutes" => 30,
                "calories" => 820,
                "protein" => 56,
                "fat" => 47,
                "carbs" => 48,
                "image" => "food/alfredo.jpg",
            ],
            [
                "name" => "Sushi Rolls",
                "description" => "DIY maki filled with seasoned sushi rice, crisp cucumber, creamy avocado and fresh crab sticks, rolled tight and served with soy-wasabi dip.",
                "ingredients" => "2 cups sushi rice (short-grain)\n2 ½ cups water\n3 Tbsp rice vinegar\n1 Tbsp sugar\n1 tsp salt\n4 nori sheets\n1 avocado (cut into strips)\n1 small cucumber (julienned)
                4 crab sticks (or surimi)
                1 Tbsp toasted sesame seeds
                Soy sauce, wasabi & pickled ginger for serving",
                "instructions" => "1. Rinse rice until water runs clear; cook with 2 ½ cups water, let steam 10 min.\n2. Heat vinegar, sugar, salt until dissolved; fold into warm rice, cool to room temp.\n3. Lay bamboo mat with plastic wrap; place nori shiny-side down.\n4. Wet fingers; spread thin rice layer over nori, sprinkle sesame seeds.\n5. Arrange crab, avocado, cucumber along bottom edge; roll tightly using mat, sealing edge with water.\n6. Slice roll into 8 pieces with wet sharp knife; serve with soy, wasabi and ginger.",
                "difficulty" => "Hard",
                "cuisine" => "Japanese",
                "time_minutes" => 40,
                "calories" => 330,
                "protein" => 9,
                "fat" => 5,
                "carbs" => 62,
                "image" => "food/sushi.jpg",
            ],
            [
                "name" => "Steak with Garlic Butter",
                "description" => "Perfectly seared rib-eye steak finished with a rich garlic-herb butter, rested and sliced for juicy, restaurant-quality bites.",
                "ingredients" => "2 rib-eye steaks (2.5 cm thick, 300 g each)\n1 ½ tsp kosher salt\n1 tsp cracked black pepper\n1 Tbsp neutral oil (high-smoke)\n3 Tbsp unsalted butter (softened)\n2 cloves garlic (minced)\n1 Tbsp fresh parsley (finely chopped)\n½ tsp fresh thyme leaves\nOptional: extra butter pat for basting",
                "instructions" => "1. Pat steaks dry; salt both sides generously 40 min before cooking (or at least 10 min).\n2. Mix softened butter, garlic, parsley, thyme; set aside.\n3. Heat cast-iron skillet to high until barely smoking; add oil.\n4. Sear steaks 2 min without moving; flip, sear 2 min more.\n5. Reduce heat to medium; add garlic-butter dollop. Tilt pan, spoon foaming butter over steaks repeatedly for 1–2 min (52 °C internal for medium-rare).\n6. Transfer to board, rest 5 min; top with remaining garlic butter, slice and serve.",
                "difficulty" => "Medium",
                "cuisine" => "Western",
                "time_minutes" => 20,
                "calories" => 620,
                "protein" => 46,
                "fat" => 48,
                "carbs" => 1,
                "image" => "food/steak.jpg",
            ],
            [
                "name" => "Veggie Stir Fry",
                "description" => "Colorful vegetable stir-fry with soy garlic sauce.",
                "ingredients" => "Broccoli\nCarrots\nBell peppers\nSoy sauce\nGarlic",
                "instructions" => "1. Stir fry veggies.\n2. Add sauce.",
                "difficulty" => "Easy",
                "cuisine" => "Asian",
                "time_minutes" => 12,
                "calories" => 200,
                "protein" => 5,
                "fat" => 4,
                "carbs" => 35,
                "image" => "food/stirfry.jpg",
            ],
            [
                "name" => "Rawon Daging Super-Lean",
                "description" => "East-Javanese beef soup tinted black with keluak, loaded with lean beef cubes and fiber-rich sprouts, simmered with zero added fat for a lighter yet aromatic bowl.",
                "ingredients" => "300 g lean beef round (2 cm cubes)\n6 cups low-sodium beef broth\n1 tsp oil (for spice sauté)\nSpice paste: 3 kluak (black nut, cleaned), 3 shallots, 2 cloves garlic, 1 thumb ginger, 1 tsp coriander seed, 3 candlenuts, 1 bird-eye chili (all blended smooth)\nAromatics: 2 salam leaves, 1 stalk lemongrass (bruised), 2 kaffir-lime leaves\nAdd-ins: 1 cup mung-bean sprouts, ½ cup chopped Chinese chives\nGarnish: sliced raw shallot, lime wedges, sambal oelek on the side",
                "instructions" => "1. Brown beef in a hot non-stick pot 3 min; add broth, spice paste, salam, lemongrass, lime leaves.\n2. Simmer covered 60 min until beef tender; skim fat periodically.\n3. Adjust salt, add sprouts & chives for 1 min to keep crunch.\n4. Serve hot over steamed brown rice (optional) with shallot slices and a squeeze of lime.",
                "difficulty" => "Medium",
                "cuisine" => "Indonesian",
                "time_minutes" => 75,
                "calories" => 280,
                "protein" => 34,
                "fat" => 9,
                "carbs" => 14,
                "image" => "food/rawon.jpg",
            ]
        ];

        foreach ($recipes as $recipe) {
            Recipe::create(array_merge($recipe, [
                "user_id" => $user->id,
                "rating" => 0,
            ]));
        }
    }
}
